language: java
jdk:
- oraclejdk8
before_install:
- mvn clean
after_success:
- mvn test jacoco:report coveralls:report
#deploy:
#  skip_cleanup: true
#  provider: heroku
#  api_key:
#    secure: @@
#  app:
#    #master: book2-app
#  on:
#    repo: zlubsen/StoredValueAccounts