sudo: required

language: java

services:
  - docker
  
jdk:
- oraclejdk8

before_install:
- mvn clean
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t zlubsen/sva .
- docker push zlubsen/sva

after_success:
- mvn test jacoco:report coveralls:report

#deploy:
#  skip_cleanup: true
#  provider: heroku
#  api_key:
#    secure: @@
#  app:
#    #master: book2-app
#  on:
#    repo: zlubsen/StoredValueAccounts